"""
gdep.wiki.node_writer
분석 결과(문자열) → YAML frontmatter + 마크다운 위키 페이지 변환.
"""
from __future__ import annotations

from datetime import date


def make_class_page(class_name: str, analysis_content: str,
                    fingerprint: str, engine: str = "") -> str:
    """explore_class_semantics 결과를 클래스 위키 페이지로 변환."""
    today = date.today().strftime("%Y-%m-%d")
    engine_line = f"engine: {engine}\n" if engine else ""
    frontmatter = (
        f"---\n"
        f"title: \"{class_name}\"\n"
        f"type: class\n"
        f"{engine_line}"
        f"created: {today}\n"
        f"updated: {today}\n"
        f"source_fingerprint: {fingerprint}\n"
        f"stale: false\n"
        f"---\n\n"
    )
    body = (
        f"# {class_name}\n\n"
        f"> Auto-generated by `explore_class_semantics`. "
        f"Re-run to update if source changes.\n\n"
        f"{analysis_content}\n"
    )
    return frontmatter + body


def make_asset_page(asset_name: str, analysis_content: str,
                    fingerprint: str, asset_kind: str = "",
                    engine: str = "") -> str:
    """에셋 분석 결과를 에셋 위키 페이지로 변환."""
    today = date.today().strftime("%Y-%m-%d")
    frontmatter = (
        f"---\n"
        f"title: \"{asset_name}\"\n"
        f"type: asset\n"
        f"asset_kind: {asset_kind}\n"
        f"engine: {engine}\n"
        f"created: {today}\n"
        f"updated: {today}\n"
        f"source_fingerprint: {fingerprint}\n"
        f"stale: false\n"
        f"---\n\n"
    )
    body = (
        f"# {asset_name}\n\n"
        f"> Auto-generated by gdep asset analysis. "
        f"Re-run to update if asset changes.\n\n"
        f"{analysis_content}\n"
    )
    return frontmatter + body


def make_system_page(system_name: str, analysis_content: str,
                     fingerprint: str, engine: str = "") -> str:
    """엔진 시스템(GAS, BT 등) 분석 결과를 시스템 위키 페이지로 변환."""
    today = date.today().strftime("%Y-%m-%d")
    frontmatter = (
        f"---\n"
        f"title: \"{system_name}\"\n"
        f"type: system\n"
        f"engine: {engine}\n"
        f"created: {today}\n"
        f"updated: {today}\n"
        f"source_fingerprint: {fingerprint}\n"
        f"stale: false\n"
        f"---\n\n"
    )
    body = (
        f"# {system_name}\n\n"
        f"> Auto-generated by gdep engine analysis. "
        f"Re-run to update when system changes.\n\n"
        f"{analysis_content}\n"
    )
    return frontmatter + body


def make_pattern_page(pattern_name: str, analysis_content: str,
                      fingerprint: str) -> str:
    """detect_patterns 결과를 패턴 위키 페이지로 변환."""
    today = date.today().strftime("%Y-%m-%d")
    frontmatter = (
        f"---\n"
        f"title: \"{pattern_name}\"\n"
        f"type: pattern\n"
        f"created: {today}\n"
        f"updated: {today}\n"
        f"source_fingerprint: {fingerprint}\n"
        f"stale: false\n"
        f"---\n\n"
    )
    body = (
        f"# Pattern: {pattern_name}\n\n"
        f"> Auto-generated by `detect_patterns`.\n\n"
        f"{analysis_content}\n"
    )
    return frontmatter + body


def make_conversation_page(title: str, content: str,
                           fingerprint: str,
                           tags: list[str] | None = None,
                           tools_used: list[str] | None = None) -> str:
    """에이전트 대화 요약을 대화 위키 페이지로 변환."""
    today = date.today().strftime("%Y-%m-%d")
    tags_line = f"tags: [{', '.join(tags)}]\n" if tags else ""
    tools_line = f"tools_used: [{', '.join(tools_used)}]\n" if tools_used else ""
    frontmatter = (
        f"---\n"
        f"title: \"{title}\"\n"
        f"type: conversation\n"
        f"session_date: {today}\n"
        f"{tags_line}"
        f"{tools_line}"
        f"created: {today}\n"
        f"updated: {today}\n"
        f"source_fingerprint: {fingerprint}\n"
        f"stale: false\n"
        f"---\n\n"
    )
    body = (
        f"# {title}\n\n"
        f"> Saved by agent via `wiki_save_conversation`.\n\n"
        f"{content}\n"
    )
    return frontmatter + body


def update_frontmatter_stale(content: str, stale: bool) -> str:
    """기존 마크다운 페이지의 frontmatter에서 stale 값을 업데이트."""
    stale_str = "true" if stale else "false"
    lines = content.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("stale:"):
            lines[i] = f"stale: {stale_str}"
            break
    return "\n".join(lines)
